# Generated by Django 3.1.4 on 2020-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=80, null=True, verbose_name='Gender')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('shoe_size', models.IntegerField()),
                ('body_picture', models.ImageField(upload_to='')),
                ('skin_picture', models.ImageField(upload_to='')),
                ('preferred_color', models.JSONField()),
                ('non_preffered_color', models.JSONField()),
            ],
        ),
    ]
